site_name: ActiveTigger Documentation
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - User Guide: documentation.md
  - Get Access: access.md
  - Software: software.md
  - Contributors: contributors.md
markdown_extensions:
  - footnotes
theme: readthedocs